name: Scrapper runs every 5 minutes
on:
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
      with:
          ref: master

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Scrap GSoC Website
      run: |
        python main.py
    
    - name: Commit file (data.json)
      run: |
        echo ${{ github.ref }}
        git add .
        git config --local user.email "muarachmann@gmail.com"
        git config --local user.name "Mua N. Laurent"
        git commit -m "scrapper: Automated build push" -a | exit 0
    
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}